# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dashboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dashboard
  pod 'PushNotifications', '~> 1.2.0'
  pod 'PusherSwift', '~> 6.1'
  pod 'Alamofire', '~> 4.8.2'
end
